/**
* AutoGenerated by @zuzjs/orm.
* @ Thu Mar 27 2025 20:20:00
*/
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column, OneToOne, JoinColumn } from "@zuzjs/orm";
import { Servers } from "./servers";
import { Users } from "./users";


@Entity({ name: "drive" })
export class Drive extends BaseEntity {

	@PrimaryGeneratedColumn()
	ID!: number;

	@Column({ type: "bigint", default: "0" })
	uid!: number;

	@Column({ type: "int", nullable: true })
	/** @comment server id from servers table */
	sid!: number;

	@Column({ type: "varchar", length: 50, default: "file" })
	type!: string;

	@Column({ type: "int", default: 0 })
	folder!: number;

	@Column({ type: "varchar", length: 255, default: "none" })
	fileid!: string;

	@Column({ type: "varchar", length: 255, default: "Untitled" })
	name!: string;

	@Column({ type: "varchar", length: 50, default: "unknown" })
	mime!: string;

	@Column({ type: "varchar", length: 100, default: "0" })
	size!: string;

	@Column({ type: "int", default: 1 })
	/** @comment 0=private,1=public,2=password */
	privacy!: number;

	@Column({ type: "varchar", length: 100, default: "none" })
	passw!: string;

	@Column({ type: "int", default: 0 })
	downs!: number;

	@Column({ type: "int", default: 0 })
	debrid!: number;

	@Column({ type: "varchar", length: 50, default: "0" })
	stamp!: string;

	@Column({ type: "int", default: 1 })
	status!: number;

	@OneToOne(() => Servers)
	@JoinColumn({ name: "sid" })
	fkServers!: Servers;

	@OneToOne(() => Users)
	@JoinColumn({ name: "uid" })
	fkUsers!: Users;

}