/**
* AutoGenerated by @zuzjs/orm.
* @ Wed Apr 09 2025 21:05:55
*/
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column } from "@zuzjs/orm";


@Entity({ name: "servers" })
export class Servers extends BaseEntity {

	@PrimaryGeneratedColumn()
	ID!: number;

	@Column({ type: "varchar", length: 20, default: "local" })
	type!: string;

	@Column({ type: "varchar", length: 100, default: "Server" })
	name!: string;

	@Column({ type: "varchar", length: 30, default: "none" })
	ipaddr!: string;

	@Column({ type: "varchar", length: 355, default: "__none__" })
	uri!: string;

	@Column({ type: "bigint", default: 0 })
	disk_total!: number;

	@Column({ type: "bigint", default: 0 })
	disk_left!: number;

	@Column({ type: "int", default: 1 })
	status!: number;

}