/**
* AutoGenerated by @zuzjs/orm.
* @ Sun Feb 23 2025 13:17:22
*/
import { Entity, PrimaryColumn, PrimaryGeneratedColumn, Column, BaseEntity } from "@zuzjs/orm";

@Entity({ name: "users" })
export class Users extends BaseEntity {

	@PrimaryGeneratedColumn()
	ID!: number;

	@Column({ type: "varchar", length: 100, default: "none" })
	token!: string;

	@Column({ type: "varchar", length: 20, default: "xxxxxx" })
	ucode!: string;

	@Column({ type: "varchar", length: 255, default: "user" })
	utype!: any;

	@Column({ type: "varchar", length: 355, default: "none" })
	permissions!: string;

	@Column({ type: "varchar", length: 155, default: "none" })
	email!: string;

	@Column({ type: "varchar", length: 155, default: "none" })
	password!: string;

	@Column({ type: "varchar", length: 100, default: "none" })
	fullname!: string;

	@Column({ type: "varchar", length: 100, default: "no-dp.png" })
	picture!: string;

	@Column({ type: "varchar", length: 255, default: "unknown" })
	gender!: any;

	@Column({ type: "varchar", length: 10, default: "00-00-0000" })
	dob!: string;

	@Column({ type: "int", nullable: true, default: 0 })
	reff!: number;

	@Column({ type: "varchar", length: 100, default: "UTC" })
	timezone!: string;

	@Column({ type: "varchar", length: 100, default: "none" })
	joined!: string;

	@Column({ type: "varchar", length: 100, default: "none" })
	signin!: string;

	@Column({ type: "int", default: 0 })
	status!: number;

}