/**
* AutoGenerated by @zuzjs/orm.
* @ Tue Dec 09 2025 22:37:31
*/
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column, OneToOne, JoinColumn } from "@zuzjs/orm";
import { Users } from "./users";
export enum Isadmin { Yes = "yes", No = "no" }
export enum Status { Yes = "yes", No = "no" }

@Entity({ name: "users_sess" })
export class UsersSess extends BaseEntity {

	@PrimaryGeneratedColumn()
	ID!: number;

	@Column({ type: "int", default: 0 })
	uid!: number;

	@Column({ type: "varchar", length: 455, default: "none" })
	token!: string;

	@Column({ type: "varchar", length: 50, default: "0" })
	expiry!: string;

	@Column({ type: "varchar", length: 255, default: "none" })
	uinfo!: string;

	@Column({ type: "enum", enum: Isadmin, default: "no" })
	isadmin!: Isadmin;

	@Column({ type: "enum", enum: Status, default: "yes" })
	status!: Status;

	@OneToOne(() => Users)
	@JoinColumn({ name: "uid" })
	fkUsers!: Users;

}