/**
* AutoGenerated by @zuzjs/orm.
* @ Sun Feb 23 2025 13:17:22
*/
import { Entity, PrimaryColumn, PrimaryGeneratedColumn, Column, BaseEntity } from "@zuzjs/orm";

@Entity({ name: "users_sess" })
export class UsersSess extends BaseEntity {

	@PrimaryGeneratedColumn()
	ID!: number;

	@Column({ type: "bigint", default: "0" })
	uid!: string;

	@Column({ type: "varchar", length: 455 })
	token!: string;

	@Column({ type: "varchar", length: 50, default: "0" })
	expiry!: string;

	@Column({ type: "varchar", length: 255, default: "none" })
	uinfo!: string;

	@Column({ type: "int", default: 0 })
	master!: number;

	@Column({ type: "int", default: 1 })
	status!: number;

}