/**
* AutoGenerated by @zuzjs/orm.
* @ Wed Apr 09 2025 21:05:55
*/
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column } from "@zuzjs/orm";


@Entity({ name: "users_sess" })
export class UsersSess extends BaseEntity {

	@PrimaryGeneratedColumn()
	ID!: number;

	@Column({ type: "bigint", default: 0 })
	uid!: number;

	@Column({ type: "varchar", length: 455 })
	token!: string;

	@Column({ type: "varchar", length: 50, default: "0" })
	expiry!: string;

	@Column({ type: "varchar", length: 255, default: "none" })
	uinfo!: string;

	@Column({ type: "int", default: 0 })
	master!: number;

	@Column({ type: "int", default: 1 })
	status!: number;

}